import type { Provider, Weather } from './Provider';
import type { Location } from './Location';

export class ExampleProvider implements Provider {
  static id = 'example';
  static description = 'Example';
  static attribution = undefined;
  static requiresLocation = false;
  static fields = [];

  async fetch(): Promise<Weather> {
    return {
      current: {
        timestamp: new Date('2023-09-17T01:00:00.000Z'),
        conditions: 'Overcast',
        conditions_icon: 3,
        temperature: 18.6,
        temperature_low: 15.3,
        temperature_high: 22.7,
        feels_like_temperature: 18.9,
        dew_point_temperature: 15.5,
        relative_humidity: 82,
        wind_speed: 10.5,
        wind_direction: 164,
        pressure: 1014.1,
        visibility: 17.1,
        hourly: [
          {
            timestamp: new Date('2023-09-17T01:00:00.000Z'),
            conditions: 'Overcast',
            conditions_icon: 3,
            temperature: 18.6,
          },
          {
            timestamp: new Date('2023-09-17T02:00:00.000Z'),
            conditions: 'Light Drizzle',
            conditions_icon: 5,
            temperature: 17.7,
          },
          {
            timestamp: new Date('2023-09-17T03:00:00.000Z'),
            conditions: 'Slight Rain',
            conditions_icon: 5,
            temperature: 16.4,
          },
          {
            timestamp: new Date('2023-09-17T04:00:00.000Z'),
            conditions: 'Dense Drizzle',
            conditions_icon: 5,
            temperature: 15.4,
          },
          {
            timestamp: new Date('2023-09-17T05:00:00.000Z'),
            conditions: 'Moderate Drizzle',
            conditions_icon: 5,
            temperature: 15.2,
          },
          {
            timestamp: new Date('2023-09-17T06:00:00.000Z'),
            conditions: 'Light Drizzle',
            conditions_icon: 5,
            temperature: 15.2,
          },
          {
            timestamp: new Date('2023-09-17T07:00:00.000Z'),
            conditions: 'Light Drizzle',
            conditions_icon: 5,
            temperature: 14.8,
          },
          {
            timestamp: new Date('2023-09-17T08:00:00.000Z'),
            conditions: 'Overcast',
            conditions_icon: 3,
            temperature: 14.5,
          },
          {
            timestamp: new Date('2023-09-17T09:00:00.000Z'),
            conditions: 'Overcast',
            conditions_icon: 3,
            temperature: 14.2,
          },
          {
            timestamp: new Date('2023-09-17T10:00:00.000Z'),
            conditions: 'Overcast',
            conditions_icon: 3,
            temperature: 14.5,
          },
          {
            timestamp: new Date('2023-09-17T11:00:00.000Z'),
            conditions: 'Overcast',
            conditions_icon: 3,
            temperature: 14.4,
          },
          {
            timestamp: new Date('2023-09-17T12:00:00.000Z'),
            conditions: 'Overcast',
            conditions_icon: 3,
            temperature: 14.5,
          },
          {
            timestamp: new Date('2023-09-17T13:00:00.000Z'),
            conditions: 'Overcast',
            conditions_icon: 3,
            temperature: 15,
          },
          {
            timestamp: new Date('2023-09-17T14:00:00.000Z'),
            conditions: 'Overcast',
            conditions_icon: 3,
            temperature: 16,
          },
          {
            timestamp: new Date('2023-09-17T15:00:00.000Z'),
            conditions: 'Overcast',
            conditions_icon: 3,
            temperature: 17.3,
          },
          {
            timestamp: new Date('2023-09-17T16:00:00.000Z'),
            conditions: 'Overcast',
            conditions_icon: 3,
            temperature: 18.5,
          },
          {
            timestamp: new Date('2023-09-17T17:00:00.000Z'),
            conditions: 'Overcast',
            conditions_icon: 3,
            temperature: 16.2,
          },
          {
            timestamp: new Date('2023-09-17T18:00:00.000Z'),
            conditions: 'Partly Cloudy',
            conditions_icon: 1,
            temperature: 20.5,
          },
          {
            timestamp: new Date('2023-09-17T19:00:00.000Z'),
            conditions: 'Partly Cloudy',
            conditions_icon: 1,
            temperature: 20.5,
          },
          {
            timestamp: new Date('2023-09-17T20:00:00.000Z'),
            conditions: 'Overcast',
            conditions_icon: 3,
            temperature: 20.8,
          },
          {
            timestamp: new Date('2023-09-17T21:00:00.000Z'),
            conditions: 'Overcast',
            conditions_icon: 3,
            temperature: 19,
          },
          {
            timestamp: new Date('2023-09-17T22:00:00.000Z'),
            conditions: 'Overcast',
            conditions_icon: 3,
            temperature: 18.7,
          },
          {
            timestamp: new Date('2023-09-17T23:00:00.000Z'),
            conditions: 'Mainly Clear',
            conditions_icon: 0,
            temperature: 19,
          },
          {
            timestamp: new Date('2023-09-18T00:00:00.000Z'),
            conditions: 'Clear Sky',
            conditions_icon: 0,
            temperature: 17.3,
          },
        ],
      },
      daily: [
        {
          timestamp: new Date('2023-09-17T05:00:00.000Z'),
          conditions: 'Moderate Drizzle',
          conditions_icon: 5,
          temperature_low: 13.3,
          temperature_high: 20.8,
          sunrise_timestamp: new Date('2023-09-17T11:38:31.000Z'),
          sunset_timestamp: new Date('2023-09-18T00:03:15.000Z'),
          precipitation_probability: 39,
          precipitation_amount: 1.5,
          hourly: [
            {
              timestamp: new Date('2023-09-17T05:00:00.000Z'),
              conditions: 'Moderate Drizzle',
              conditions_icon: 5,
              temperature: 15.2,
              wind_speed: 9,
              wind_direction: 360,
              precipitation_probability: 30,
              precipitation_amount: 0.7,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-17T06:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 15.2,
              wind_speed: 5.8,
              wind_direction: 30,
              precipitation_probability: 23,
              precipitation_amount: 0.4,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-17T07:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 14.8,
              wind_speed: 7.6,
              wind_direction: 360,
              precipitation_probability: 22,
              precipitation_amount: 0.4,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-17T08:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 14.5,
              wind_speed: 5.8,
              wind_direction: 97,
              precipitation_probability: 20,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T09:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 14.2,
              wind_speed: 4.4,
              wind_direction: 35,
              precipitation_probability: 19,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T10:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 14.5,
              wind_speed: 2.3,
              wind_direction: 72,
              precipitation_probability: 15,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T11:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 14.4,
              wind_speed: 2.6,
              wind_direction: 326,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T12:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 14.5,
              wind_speed: 2.6,
              wind_direction: 326,
              precipitation_probability: 6,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T13:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 15,
              wind_speed: 4.1,
              wind_direction: 345,
              precipitation_probability: 6,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T14:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 16,
              wind_speed: 6.8,
              wind_direction: 342,
              precipitation_probability: 6,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T15:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 17.3,
              wind_speed: 8.6,
              wind_direction: 360,
              precipitation_probability: 6,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T16:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 18.5,
              wind_speed: 11.3,
              wind_direction: 7,
              precipitation_probability: 17,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T17:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 16.2,
              wind_speed: 8.8,
              wind_direction: 71,
              precipitation_probability: 28,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T18:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 20.5,
              wind_speed: 14.1,
              wind_direction: 40,
              precipitation_probability: 39,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T19:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 20.5,
              wind_speed: 13.4,
              wind_direction: 24,
              precipitation_probability: 39,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T20:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 20.8,
              wind_speed: 17.7,
              wind_direction: 356,
              precipitation_probability: 39,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T21:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 19,
              wind_speed: 13.8,
              wind_direction: 7,
              precipitation_probability: 39,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T22:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 18.7,
              wind_speed: 11.6,
              wind_direction: 22,
              precipitation_probability: 31,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-17T23:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 19,
              wind_speed: 8,
              wind_direction: 27,
              precipitation_probability: 24,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T00:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 17.3,
              wind_speed: 5.8,
              wind_direction: 353,
              precipitation_probability: 16,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T01:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 15.7,
              wind_speed: 5.2,
              wind_direction: 295,
              precipitation_probability: 11,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T02:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 14.7,
              wind_speed: 7.3,
              wind_direction: 101,
              precipitation_probability: 5,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T03:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 14.1,
              wind_speed: 7.3,
              wind_direction: 99,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T04:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 13.3,
              wind_speed: 6.8,
              wind_direction: 108,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
          ],
        },
        {
          timestamp: new Date('2023-09-18T05:00:00.000Z'),
          conditions: 'Overcast',
          conditions_icon: 3,
          temperature_low: 12.1,
          temperature_high: 25.9,
          sunrise_timestamp: new Date('2023-09-18T11:39:34.000Z'),
          sunset_timestamp: new Date('2023-09-19T00:01:30.000Z'),
          precipitation_probability: 3,
          precipitation_amount: 0,
          hourly: [
            {
              timestamp: new Date('2023-09-18T05:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 12.7,
              wind_speed: 5,
              wind_direction: 120,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T06:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 12.2,
              wind_speed: 3.2,
              wind_direction: 180,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T07:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 12.7,
              wind_speed: 4.1,
              wind_direction: 285,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T08:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 12.7,
              wind_speed: 3.3,
              wind_direction: 131,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T09:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 12.4,
              wind_speed: 4.8,
              wind_direction: 27,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T10:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 12.7,
              wind_speed: 3.4,
              wind_direction: 122,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T11:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 12.1,
              wind_speed: 1.9,
              wind_direction: 292,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T12:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 12.6,
              wind_speed: 3.2,
              wind_direction: 297,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T13:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 13.1,
              wind_speed: 0.5,
              wind_direction: 225,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T14:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 14.4,
              wind_speed: 2.5,
              wind_direction: 278,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T15:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 16.4,
              wind_speed: 5.5,
              wind_direction: 212,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T16:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 17.9,
              wind_speed: 6,
              wind_direction: 205,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T17:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 19.2,
              wind_speed: 9.3,
              wind_direction: 216,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T18:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 19.1,
              wind_speed: 5.9,
              wind_direction: 313,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T19:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 25,
              wind_speed: 11.7,
              wind_direction: 225,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T20:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 25.7,
              wind_speed: 11.7,
              wind_direction: 227,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T21:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 25.9,
              wind_speed: 11.7,
              wind_direction: 225,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T22:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 25.6,
              wind_speed: 11.9,
              wind_direction: 215,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-18T23:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 24.2,
              wind_speed: 10.4,
              wind_direction: 194,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T00:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 19.9,
              wind_speed: 10.5,
              wind_direction: 184,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T01:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 17.7,
              wind_speed: 9.2,
              wind_direction: 129,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T02:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 14.8,
              wind_speed: 15,
              wind_direction: 111,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T03:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 14.5,
              wind_speed: 16.5,
              wind_direction: 126,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T04:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 14.6,
              wind_speed: 16.3,
              wind_direction: 131,
              precipitation_probability: 3,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
          ],
        },
        {
          timestamp: new Date('2023-09-19T05:00:00.000Z'),
          conditions: 'Overcast',
          conditions_icon: 3,
          temperature_low: 14.7,
          temperature_high: 30.5,
          sunrise_timestamp: new Date('2023-09-19T11:40:37.000Z'),
          sunset_timestamp: new Date('2023-09-19T23:59:43.000Z'),
          precipitation_probability: 39,
          precipitation_amount: 0,
          hourly: [
            {
              timestamp: new Date('2023-09-19T05:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 14.9,
              wind_speed: 16.9,
              wind_direction: 142,
              precipitation_probability: 7,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T06:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 15,
              wind_speed: 18.5,
              wind_direction: 151,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T07:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 14.7,
              wind_speed: 15.2,
              wind_direction: 149,
              precipitation_probability: 17,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T08:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 14.9,
              wind_speed: 15.3,
              wind_direction: 141,
              precipitation_probability: 25,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T09:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 15.1,
              wind_speed: 15.9,
              wind_direction: 147,
              precipitation_probability: 32,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T10:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 15.6,
              wind_speed: 21.1,
              wind_direction: 143,
              precipitation_probability: 34,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T11:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 16.3,
              wind_speed: 9.8,
              wind_direction: 156,
              precipitation_probability: 37,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T12:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 15.7,
              wind_speed: 15.1,
              wind_direction: 142,
              precipitation_probability: 39,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T13:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 16.6,
              wind_speed: 17.3,
              wind_direction: 138,
              precipitation_probability: 36,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T14:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 18.2,
              wind_speed: 14.1,
              wind_direction: 142,
              precipitation_probability: 32,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T15:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 19.6,
              wind_speed: 19.5,
              wind_direction: 142,
              precipitation_probability: 29,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T16:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 23.4,
              wind_speed: 24.5,
              wind_direction: 158,
              precipitation_probability: 30,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T17:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 26.9,
              wind_speed: 28.6,
              wind_direction: 161,
              precipitation_probability: 31,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T18:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 28.9,
              wind_speed: 29.4,
              wind_direction: 172,
              precipitation_probability: 32,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T19:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 29.8,
              wind_speed: 30.2,
              wind_direction: 179,
              precipitation_probability: 25,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T20:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 30.5,
              wind_speed: 29.2,
              wind_direction: 182,
              precipitation_probability: 17,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T21:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 30.5,
              wind_speed: 28.4,
              wind_direction: 181,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T22:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 30.3,
              wind_speed: 22.7,
              wind_direction: 177,
              precipitation_probability: 8,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-19T23:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 29.4,
              wind_speed: 20.1,
              wind_direction: 165,
              precipitation_probability: 5,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T00:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 24.9,
              wind_speed: 15.6,
              wind_direction: 140,
              precipitation_probability: 3,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T01:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 21.1,
              wind_speed: 17.1,
              wind_direction: 112,
              precipitation_probability: 7,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T02:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 20.5,
              wind_speed: 18.4,
              wind_direction: 130,
              precipitation_probability: 12,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T03:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 22.6,
              wind_speed: 22.7,
              wind_direction: 157,
              precipitation_probability: 16,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T04:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 23.1,
              wind_speed: 23.7,
              wind_direction: 170,
              precipitation_probability: 17,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
          ],
        },
        {
          timestamp: new Date('2023-09-20T05:00:00.000Z'),
          conditions: 'Dense Drizzle',
          conditions_icon: 5,
          temperature_low: 15.4,
          temperature_high: 30.9,
          sunrise_timestamp: new Date('2023-09-20T11:41:40.000Z'),
          sunset_timestamp: new Date('2023-09-20T23:57:57.000Z'),
          precipitation_probability: 19,
          precipitation_amount: 4,
          hourly: [
            {
              timestamp: new Date('2023-09-20T05:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 23.1,
              wind_speed: 24.1,
              wind_direction: 183,
              precipitation_probability: 18,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T06:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 22.2,
              wind_speed: 22.1,
              wind_direction: 186,
              precipitation_probability: 19,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T07:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 19.6,
              wind_speed: 20.5,
              wind_direction: 177,
              precipitation_probability: 16,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T08:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 16.8,
              wind_speed: 18.6,
              wind_direction: 171,
              precipitation_probability: 13,
              precipitation_amount: 0.2,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-20T09:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 17.6,
              wind_speed: 18.4,
              wind_direction: 176,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T10:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 18.1,
              wind_speed: 21.7,
              wind_direction: 187,
              precipitation_probability: 13,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-20T11:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 15.9,
              wind_speed: 17.7,
              wind_direction: 185,
              precipitation_probability: 16,
              precipitation_amount: 0.4,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-20T12:00:00.000Z'),
              conditions: 'Dense Drizzle',
              conditions_icon: 5,
              temperature: 15.4,
              wind_speed: 12.8,
              wind_direction: 191,
              precipitation_probability: 19,
              precipitation_amount: 1.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-20T13:00:00.000Z'),
              conditions: 'Moderate Drizzle',
              conditions_icon: 5,
              temperature: 16.4,
              wind_speed: 11.8,
              wind_direction: 192,
              precipitation_probability: 17,
              precipitation_amount: 0.9,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-20T14:00:00.000Z'),
              conditions: 'Moderate Drizzle',
              conditions_icon: 5,
              temperature: 18,
              wind_speed: 14.3,
              wind_direction: 190,
              precipitation_probability: 15,
              precipitation_amount: 0.8,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-20T15:00:00.000Z'),
              conditions: 'Moderate Drizzle',
              conditions_icon: 5,
              temperature: 19.8,
              wind_speed: 14,
              wind_direction: 192,
              precipitation_probability: 13,
              precipitation_amount: 0.5,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-20T16:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 20.6,
              wind_speed: 12.8,
              wind_direction: 191,
              precipitation_probability: 9,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T17:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 22.3,
              wind_speed: 15.8,
              wind_direction: 181,
              precipitation_probability: 4,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T18:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 26.1,
              wind_speed: 15.1,
              wind_direction: 177,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T19:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 30,
              wind_speed: 16.3,
              wind_direction: 186,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T20:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 30.9,
              wind_speed: 19.6,
              wind_direction: 194,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T21:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 30.9,
              wind_speed: 20.1,
              wind_direction: 189,
              precipitation_probability: 0,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T22:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 29.5,
              wind_speed: 23.3,
              wind_direction: 202,
              precipitation_probability: 1,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-20T23:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 26.5,
              wind_speed: 14.8,
              wind_direction: 209,
              precipitation_probability: 2,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T00:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 22.8,
              wind_speed: 6.6,
              wind_direction: 221,
              precipitation_probability: 3,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T01:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 21.4,
              wind_speed: 10.4,
              wind_direction: 250,
              precipitation_probability: 3,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T02:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 20.2,
              wind_speed: 11.8,
              wind_direction: 243,
              precipitation_probability: 3,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T03:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 19.7,
              wind_speed: 7,
              wind_direction: 291,
              precipitation_probability: 3,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T04:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 19.3,
              wind_speed: 5.3,
              wind_direction: 298,
              precipitation_probability: 3,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
          ],
        },
        {
          timestamp: new Date('2023-09-21T05:00:00.000Z'),
          conditions: 'Overcast',
          conditions_icon: 3,
          temperature_low: 17.1,
          temperature_high: 30.4,
          sunrise_timestamp: new Date('2023-09-21T11:42:44.000Z'),
          sunset_timestamp: new Date('2023-09-21T23:56:10.000Z'),
          precipitation_probability: 23,
          precipitation_amount: 0,
          hourly: [
            {
              timestamp: new Date('2023-09-21T05:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 17.8,
              wind_speed: 4,
              wind_direction: 260,
              precipitation_probability: 3,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T06:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 17.5,
              wind_speed: 3.6,
              wind_direction: 96,
              precipitation_probability: 3,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T07:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 17.1,
              wind_speed: 4,
              wind_direction: 90,
              precipitation_probability: 6,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T08:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 17.5,
              wind_speed: 7,
              wind_direction: 78,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T09:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 17.3,
              wind_speed: 6.1,
              wind_direction: 130,
              precipitation_probability: 13,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T10:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 18.5,
              wind_speed: 6.4,
              wind_direction: 133,
              precipitation_probability: 14,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T11:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 18.8,
              wind_speed: 9.5,
              wind_direction: 119,
              precipitation_probability: 15,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T12:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 17.2,
              wind_speed: 12,
              wind_direction: 111,
              precipitation_probability: 16,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T13:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 19.3,
              wind_speed: 11.7,
              wind_direction: 99,
              precipitation_probability: 18,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T14:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 22.3,
              wind_speed: 12.3,
              wind_direction: 148,
              precipitation_probability: 21,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T15:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 24.6,
              wind_speed: 13,
              wind_direction: 161,
              precipitation_probability: 23,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T16:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 27.1,
              wind_speed: 13,
              wind_direction: 166,
              precipitation_probability: 21,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T17:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 28.9,
              wind_speed: 13.3,
              wind_direction: 193,
              precipitation_probability: 18,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T18:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 29.6,
              wind_speed: 13,
              wind_direction: 208,
              precipitation_probability: 16,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T19:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 30.2,
              wind_speed: 15.9,
              wind_direction: 208,
              precipitation_probability: 14,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T20:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 30.4,
              wind_speed: 18.8,
              wind_direction: 206,
              precipitation_probability: 12,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T21:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 29.9,
              wind_speed: 20.1,
              wind_direction: 204,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T22:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 28.3,
              wind_speed: 17.6,
              wind_direction: 206,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-21T23:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 26,
              wind_speed: 13,
              wind_direction: 208,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T00:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 24.3,
              wind_speed: 8.9,
              wind_direction: 207,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T01:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 23.5,
              wind_speed: 6.6,
              wind_direction: 189,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T02:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 23.3,
              wind_speed: 6.5,
              wind_direction: 161,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T03:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 23.1,
              wind_speed: 7.9,
              wind_direction: 141,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T04:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 22.8,
              wind_speed: 9.4,
              wind_direction: 133,
              precipitation_probability: 11,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
          ],
        },
        {
          timestamp: new Date('2023-09-22T05:00:00.000Z'),
          conditions: 'Moderate Drizzle',
          conditions_icon: 5,
          temperature_low: 18.8,
          temperature_high: 31.3,
          sunrise_timestamp: new Date('2023-09-22T11:43:48.000Z'),
          sunset_timestamp: new Date('2023-09-22T23:54:22.000Z'),
          precipitation_probability: 19,
          precipitation_amount: 2.1,
          hourly: [
            {
              timestamp: new Date('2023-09-22T05:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 22.7,
              wind_speed: 10.7,
              wind_direction: 132,
              precipitation_probability: 12,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T06:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 22.5,
              wind_speed: 11.5,
              wind_direction: 134,
              precipitation_probability: 13,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T07:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 22.2,
              wind_speed: 11,
              wind_direction: 142,
              precipitation_probability: 15,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T08:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 21.9,
              wind_speed: 10.3,
              wind_direction: 155,
              precipitation_probability: 17,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T09:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 21.5,
              wind_speed: 10.1,
              wind_direction: 163,
              precipitation_probability: 19,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T10:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 20.3,
              wind_speed: 10.2,
              wind_direction: 157,
              precipitation_probability: 19,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T11:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 19,
              wind_speed: 10.7,
              wind_direction: 147,
              precipitation_probability: 19,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T12:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 18.8,
              wind_speed: 12.4,
              wind_direction: 144,
              precipitation_probability: 19,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T13:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 20.4,
              wind_speed: 15.6,
              wind_direction: 151,
              precipitation_probability: 18,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T14:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 23.1,
              wind_speed: 20.1,
              wind_direction: 159,
              precipitation_probability: 17,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T15:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 25.6,
              wind_speed: 23.6,
              wind_direction: 164,
              precipitation_probability: 16,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T16:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 27.4,
              wind_speed: 24.9,
              wind_direction: 169,
              precipitation_probability: 16,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T17:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 28.9,
              wind_speed: 24.9,
              wind_direction: 175,
              precipitation_probability: 16,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T18:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 30.1,
              wind_speed: 24.8,
              wind_direction: 181,
              precipitation_probability: 16,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T19:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 30.9,
              wind_speed: 25,
              wind_direction: 187,
              precipitation_probability: 15,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T20:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 31.3,
              wind_speed: 24.7,
              wind_direction: 193,
              precipitation_probability: 14,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T21:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 31.1,
              wind_speed: 23.6,
              wind_direction: 196,
              precipitation_probability: 13,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T22:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 29.8,
              wind_speed: 20.6,
              wind_direction: 196,
              precipitation_probability: 15,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-22T23:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 27.8,
              wind_speed: 16.2,
              wind_direction: 193,
              precipitation_probability: 17,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T00:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 25.7,
              wind_speed: 13.1,
              wind_direction: 188,
              precipitation_probability: 19,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T01:00:00.000Z'),
              conditions: 'Moderate Drizzle',
              conditions_icon: 5,
              temperature: 23.5,
              wind_speed: 12.3,
              wind_direction: 183,
              precipitation_probability: 19,
              precipitation_amount: 0.7,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-23T02:00:00.000Z'),
              conditions: 'Moderate Drizzle',
              conditions_icon: 5,
              temperature: 21.3,
              wind_speed: 12.6,
              wind_direction: 178,
              precipitation_probability: 19,
              precipitation_amount: 0.7,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-23T03:00:00.000Z'),
              conditions: 'Moderate Drizzle',
              conditions_icon: 5,
              temperature: 19.7,
              wind_speed: 13.3,
              wind_direction: 178,
              precipitation_probability: 19,
              precipitation_amount: 0.7,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-23T04:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 19,
              wind_speed: 13.7,
              wind_direction: 185,
              precipitation_probability: 19,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
          ],
        },
        {
          timestamp: new Date('2023-09-23T05:00:00.000Z'),
          conditions: 'Light Drizzle',
          conditions_icon: 5,
          temperature_low: 16.5,
          temperature_high: 31.5,
          sunrise_timestamp: new Date('2023-09-23T11:44:52.000Z'),
          sunset_timestamp: new Date('2023-09-23T23:52:35.000Z'),
          precipitation_probability: 30,
          precipitation_amount: 0.2,
          hourly: [
            {
              timestamp: new Date('2023-09-23T05:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 18.8,
              wind_speed: 14.7,
              wind_direction: 191,
              precipitation_probability: 19,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T06:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 18.6,
              wind_speed: 15.4,
              wind_direction: 196,
              precipitation_probability: 19,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T07:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 18,
              wind_speed: 14.7,
              wind_direction: 197,
              precipitation_probability: 19,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T08:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 17.5,
              wind_speed: 13.7,
              wind_direction: 194,
              precipitation_probability: 19,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T09:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 17.1,
              wind_speed: 12.8,
              wind_direction: 191,
              precipitation_probability: 19,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T10:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 16.7,
              wind_speed: 12.4,
              wind_direction: 188,
              precipitation_probability: 17,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T11:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 16.5,
              wind_speed: 12.6,
              wind_direction: 185,
              precipitation_probability: 15,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T12:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 17.2,
              wind_speed: 13.4,
              wind_direction: 186,
              precipitation_probability: 13,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T13:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 19.3,
              wind_speed: 15.5,
              wind_direction: 192,
              precipitation_probability: 12,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T14:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 22.3,
              wind_speed: 18.7,
              wind_direction: 199,
              precipitation_probability: 11,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T15:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 25,
              wind_speed: 21.5,
              wind_direction: 203,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T16:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 27.1,
              wind_speed: 23.4,
              wind_direction: 203,
              precipitation_probability: 8,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T17:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 29,
              wind_speed: 25.2,
              wind_direction: 202,
              precipitation_probability: 5,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T18:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 30.4,
              wind_speed: 26,
              wind_direction: 202,
              precipitation_probability: 3,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T19:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 31.2,
              wind_speed: 25.9,
              wind_direction: 205,
              precipitation_probability: 6,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T20:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 31.5,
              wind_speed: 25.5,
              wind_direction: 211,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T21:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 31.2,
              wind_speed: 23.8,
              wind_direction: 212,
              precipitation_probability: 13,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T22:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 29.9,
              wind_speed: 19.8,
              wind_direction: 205,
              precipitation_probability: 14,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-23T23:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 28,
              wind_speed: 15.3,
              wind_direction: 188,
              precipitation_probability: 15,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-24T00:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 26.3,
              wind_speed: 13.5,
              wind_direction: 171,
              precipitation_probability: 16,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-24T01:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 25,
              wind_speed: 13.4,
              wind_direction: 166,
              precipitation_probability: 20,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-24T02:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 24,
              wind_speed: 13.1,
              wind_direction: 171,
              precipitation_probability: 25,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-24T03:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 23,
              wind_speed: 13.8,
              wind_direction: 174,
              precipitation_probability: 29,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-24T04:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 22.1,
              wind_speed: 14.4,
              wind_direction: 176,
              precipitation_probability: 30,
              precipitation_amount: 0.2,
              precipitation_type: 1,
            },
          ],
        },
        {
          timestamp: new Date('2023-09-24T05:00:00.000Z'),
          conditions: 'Moderate Drizzle',
          conditions_icon: 5,
          temperature_low: 17,
          temperature_high: 27.6,
          sunrise_timestamp: new Date('2023-09-24T11:45:56.000Z'),
          sunset_timestamp: new Date('2023-09-24T23:50:48.000Z'),
          precipitation_probability: 32,
          precipitation_amount: 5.8,
          hourly: [
            {
              timestamp: new Date('2023-09-24T05:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 21.3,
              wind_speed: 15.5,
              wind_direction: 177,
              precipitation_probability: 31,
              precipitation_amount: 0.2,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T06:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 20.5,
              wind_speed: 16.2,
              wind_direction: 177,
              precipitation_probability: 32,
              precipitation_amount: 0.2,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T07:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 19.5,
              wind_speed: 15.5,
              wind_direction: 175,
              precipitation_probability: 26,
              precipitation_amount: 0.4,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T08:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 18.6,
              wind_speed: 14.6,
              wind_direction: 171,
              precipitation_probability: 19,
              precipitation_amount: 0.4,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T09:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 17.9,
              wind_speed: 13.9,
              wind_direction: 170,
              precipitation_probability: 13,
              precipitation_amount: 0.4,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T10:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 17.3,
              wind_speed: 13.6,
              wind_direction: 169,
              precipitation_probability: 12,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-24T11:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 17,
              wind_speed: 13.4,
              wind_direction: 172,
              precipitation_probability: 11,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-24T12:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 17.3,
              wind_speed: 13.7,
              wind_direction: 177,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-24T13:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 18.6,
              wind_speed: 15.5,
              wind_direction: 185,
              precipitation_probability: 11,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T14:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 20.7,
              wind_speed: 18.2,
              wind_direction: 194,
              precipitation_probability: 12,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T15:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 22.7,
              wind_speed: 20.7,
              wind_direction: 200,
              precipitation_probability: 13,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T16:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 24.8,
              wind_speed: 22.9,
              wind_direction: 206,
              precipitation_probability: 12,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T17:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 26.8,
              wind_speed: 24.9,
              wind_direction: 211,
              precipitation_probability: 11,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T18:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 27.6,
              wind_speed: 24.8,
              wind_direction: 216,
              precipitation_probability: 10,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T19:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 25.9,
              wind_speed: 20.9,
              wind_direction: 221,
              precipitation_probability: 10,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T20:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 23,
              wind_speed: 15.1,
              wind_direction: 230,
              precipitation_probability: 10,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T21:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 20.6,
              wind_speed: 11.2,
              wind_direction: 237,
              precipitation_probability: 10,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T22:00:00.000Z'),
              conditions: 'Moderate Drizzle',
              conditions_icon: 5,
              temperature: 19.5,
              wind_speed: 9.9,
              wind_direction: 224,
              precipitation_probability: 11,
              precipitation_amount: 0.7,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-24T23:00:00.000Z'),
              conditions: 'Moderate Drizzle',
              conditions_icon: 5,
              temperature: 19.1,
              wind_speed: 11.4,
              wind_direction: 198,
              precipitation_probability: 12,
              precipitation_amount: 0.7,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-25T00:00:00.000Z'),
              conditions: 'Moderate Drizzle',
              conditions_icon: 5,
              temperature: 18.8,
              wind_speed: 13.1,
              wind_direction: 188,
              precipitation_probability: 13,
              precipitation_amount: 0.7,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-25T01:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 18.6,
              wind_speed: 13.1,
              wind_direction: 188,
              precipitation_probability: 14,
              precipitation_amount: 0.4,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-25T02:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 18.7,
              wind_speed: 11.9,
              wind_direction: 194,
              precipitation_probability: 15,
              precipitation_amount: 0.4,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-25T03:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 18.6,
              wind_speed: 10.8,
              wind_direction: 201,
              precipitation_probability: 16,
              precipitation_amount: 0.4,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-25T04:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 18.2,
              wind_speed: 10.2,
              wind_direction: 212,
              precipitation_probability: 18,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
          ],
        },
        {
          timestamp: new Date('2023-09-25T05:00:00.000Z'),
          conditions: 'Light Drizzle',
          conditions_icon: 5,
          temperature_low: 14.7,
          temperature_high: 27.6,
          sunrise_timestamp: new Date('2023-09-25T11:47:00.000Z'),
          sunset_timestamp: new Date('2023-09-25T23:49:01.000Z'),
          precipitation_probability: 29,
          precipitation_amount: 0.6,
          hourly: [
            {
              timestamp: new Date('2023-09-25T05:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 17.7,
              wind_speed: 9.7,
              wind_direction: 228,
              precipitation_probability: 21,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T06:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 17.3,
              wind_speed: 9.6,
              wind_direction: 236,
              precipitation_probability: 23,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T07:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 16.9,
              wind_speed: 9,
              wind_direction: 233,
              precipitation_probability: 25,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T08:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 16.6,
              wind_speed: 8.1,
              wind_direction: 225,
              precipitation_probability: 27,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T09:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 16.3,
              wind_speed: 7.4,
              wind_direction: 219,
              precipitation_probability: 29,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T10:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 15.5,
              wind_speed: 7.1,
              wind_direction: 229,
              precipitation_probability: 29,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T11:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 14.7,
              wind_speed: 7.2,
              wind_direction: 243,
              precipitation_probability: 29,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T12:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 14.8,
              wind_speed: 7.8,
              wind_direction: 248,
              precipitation_probability: 29,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T13:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 16.3,
              wind_speed: 7.3,
              wind_direction: 237,
              precipitation_probability: 24,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T14:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 18.7,
              wind_speed: 7.5,
              wind_direction: 215,
              precipitation_probability: 18,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T15:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 21.1,
              wind_speed: 8.9,
              wind_direction: 207,
              precipitation_probability: 13,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T16:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 23.2,
              wind_speed: 11.7,
              wind_direction: 214,
              precipitation_probability: 12,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T17:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 25.3,
              wind_speed: 15.5,
              wind_direction: 224,
              precipitation_probability: 11,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T18:00:00.000Z'),
              conditions: 'Mainly Clear',
              conditions_icon: 0,
              temperature: 26.8,
              wind_speed: 18.6,
              wind_direction: 229,
              precipitation_probability: 10,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T19:00:00.000Z'),
              conditions: 'Partly Cloudy',
              conditions_icon: 1,
              temperature: 27.5,
              wind_speed: 20.7,
              wind_direction: 231,
              precipitation_probability: 11,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T20:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 27.6,
              wind_speed: 21.6,
              wind_direction: 233,
              precipitation_probability: 12,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T21:00:00.000Z'),
              conditions: 'Overcast',
              conditions_icon: 3,
              temperature: 26.9,
              wind_speed: 21.3,
              wind_direction: 236,
              precipitation_probability: 13,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
            {
              timestamp: new Date('2023-09-25T22:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 24.9,
              wind_speed: 18.5,
              wind_direction: 243,
              precipitation_probability: 14,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-25T23:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 22,
              wind_speed: 14.5,
              wind_direction: 256,
              precipitation_probability: 15,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-26T00:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 19.6,
              wind_speed: 11.2,
              wind_direction: 264,
              precipitation_probability: 16,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-26T01:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 18,
              wind_speed: 7.6,
              wind_direction: 245,
              precipitation_probability: 15,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-26T02:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 16.9,
              wind_speed: 8.1,
              wind_direction: 193,
              precipitation_probability: 14,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-26T03:00:00.000Z'),
              conditions: 'Light Drizzle',
              conditions_icon: 5,
              temperature: 16,
              wind_speed: 10.9,
              wind_direction: 172,
              precipitation_probability: 13,
              precipitation_amount: 0.1,
              precipitation_type: 1,
            },
            {
              timestamp: new Date('2023-09-26T04:00:00.000Z'),
              conditions: 'Clear Sky',
              conditions_icon: 0,
              temperature: 15.3,
              wind_speed: 9.4,
              wind_direction: 176,
              precipitation_probability: 13,
              precipitation_amount: 0,
              precipitation_type: 0,
            },
          ],
        },
      ],
    };
  }

  static fromParams(_: { [key: string]: string }, __?: Location): Provider | null {
    return new ExampleProvider();
  }
}
